import Navbar from "@/Components/global/Navbar";
import ReactQueryProvider from "@/Components/global/ReactQueryProvider";
import Footer from "@/Components/global/Footer";
import Providers from "@/Components/global/Providers";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black">
        <Providers>
          <Navbar />
          <ReactQueryProvider>{children}</ReactQueryProvider>
          <Toaster position="top-right" reverseOrder={false} />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
